apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: workspacedev
  labels:
    app: adminer
spec:
  type: LoadBalancer
  ports:
    - port: 8180
      targetPort: 8080
  selector:
    app: adminer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: workspacedev
  labels:
    app: adminer
  annotations:
    kubesphere.io/creator: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
      annotations:
        kubesphere.io/creator: admin
    spec:
      containers:
        - name: adminer
          image: adminer:latest
          ports:
            - containerPort: 8080
